// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProgrammersAPI.Migrations
{
    [DbContext(typeof(ProgrammerDbContext))]
    partial class ProgrammerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Programmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceYrs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MobileDev")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Programmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeName = "KyleSams",
                            ExperienceYrs = 1,
                            FullName = "Winfred Agyekum",
                            MobileDev = false,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            CodeName = "",
                            ExperienceYrs = 3,
                            FullName = "Samuel",
                            MobileDev = true,
                            PortfolioUrl = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
